Resources:
  setLakeFormationAdmin:
    DependsOn:
      - lakeFormationMaintainanceRole
    Type: "AWS::LakeFormation::DataLakeSettings"
    Properties:
      Admins: 
        - DataLakePrincipalIdentifier: "arn:aws:iam::${self:custom.accountId}:role/lakeformation-maintainance-role"
      TrustedResourceOwners:
        - '${self:custom.accountId}'
         
