Resources:
  tableMaintainancePermissionDatabase:
    Type: "AWS::LakeFormation::PrincipalPermissions"
    Properties:
      Catalog: ${self:custom.accountId}
      Principal:
        DataLakePrincipalIdentifier: "arn:aws:iam::${self:custom.accountId}:role/table-maintainance-role"
      Permissions:
        - "CREATE_TABLE"
        - "DESCRIBE"
      PermissionsWithGrantOption: []
      Resource:
        LFTagPolicy:
          CatalogId: ${self:custom.accountId}
          ResourceType: "DATABASE"
          Expression:
            - TagKey: ${self:custom.tagKey}
              TagValues:
                - all

  tableMaintainancePermissionLocation:
    Type: "AWS::LakeFormation::PrincipalPermissions"
    Properties:
      Catalog: ${self:custom.accountId}
      Principal:
        DataLakePrincipalIdentifier: "arn:aws:iam::${self:custom.accountId}:role/table-maintainance-role"
      Permissions:
        - "DATA_LOCATION_ACCESS"
      PermissionsWithGrantOption: []
      Resource:
        DataLocation:
          CatalogId: ${self:custom.accountId}
          ResourceArn: "arn:aws:s3:::${self:custom.bucketName}"
